version: '3.1'

services:
  mysql:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Wzy020421$123456
    volumes:
      -./docker_data/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
      -./docker_data/var/lib/mysql/:/var/lib/mysql
