package com.cncounter.mysqldemo.model;

/**
 * Database Table Remarks:
 *   订单信息表
 */
public class TBizOrder {
    /**
     * Database Column Remarks:
     *   自增主键;订单id
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户userId
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   订单状态;参考OrderStateEnum
     */
    private Integer state;

    /**
     * Database Column Remarks:
     *   下单时间
     */
    private Long createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_biz_order.id
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_biz_order.id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_biz_order.user_id
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_biz_order.user_id
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_biz_order.state
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_biz_order.state
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_biz_order.create_time
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_biz_order.create_time
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_biz_order.update_time
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_biz_order.update_time
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}